version: "3.8"
services:
  backend:
    container_name: backend_sethub
    build: 
      context: .
    depends_on:
      - database
    env_file:
      - ./.env
    ports:
      - 8000:8000
    restart: always
    volumes:
      - backend_static_volume:/usr/src/sethub/frontend/src/assets
    networks:
      - network
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./.env
  database:
    container_name: database_sethub
    image: postgres:16.1-alpine3.19
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database_volume:/var/lib/postgresql/data/
    networks:
      - network

volumes:
  database_volume:
  beckend_static_volume:


networks:
  network:
    driver: bridge