version: "3.8"
services:
  web:
    container_name: web_sethub
    build: 
      context: .
    depends_on:
      - database
    env_file:
      - ./.env
    ports:
      - 8000:8000
    restart: always
    volumes:
      - web_static_volume:/usr/src/sethub/frontend/static
    networks:
      - network

  database:
    container_name: database_sethub
    image: postgres:16.1-alpine3.19
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database_volume:/var/lib/postgresql/data/
    networks:
      - network

volumes:
  database_volume:
  web_static_volume:


networks:
  network:
    driver: bridge